// Mocks generated by Mockito 5.4.6 from annotations
// in vai_ter_fogos_hoje/test/fireworks_calendar_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vai_ter_fogos_hoje/fireworks_events.dart' as _i5;
import 'package:vai_ter_fogos_hoje/services/holiday_service.dart' as _i3;
import 'package:vai_ter_fogos_hoje/services/soccer_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HolidayService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHolidayService extends _i1.Mock implements _i3.HolidayService {
  MockHolidayService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i4.Future<Map<DateTime, List<_i5.FireworksEvent>>> fetchHolidays(
    int? year,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchHolidays, [year]),
            returnValue:
                _i4.Future<Map<DateTime, List<_i5.FireworksEvent>>>.value(
                  <DateTime, List<_i5.FireworksEvent>>{},
                ),
          )
          as _i4.Future<Map<DateTime, List<_i5.FireworksEvent>>>);
}

/// A class which mocks [SoccerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoccerService extends _i1.Mock implements _i6.SoccerService {
  MockSoccerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<DateTime, List<_i5.FireworksEvent>>> fetchSoccerEvents(
    int? year,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSoccerEvents, [year]),
            returnValue:
                _i4.Future<Map<DateTime, List<_i5.FireworksEvent>>>.value(
                  <DateTime, List<_i5.FireworksEvent>>{},
                ),
          )
          as _i4.Future<Map<DateTime, List<_i5.FireworksEvent>>>);
}
